# Generated by Django 3.2.15 on 2023-01-21 13:40

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Mobile Phone')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotteryNumber', models.BigIntegerField(null=True, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('blue_count', models.IntegerField(default=0)),
                ('green_count', models.IntegerField(default=0)),
                ('red_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Mobile Phone')),
                ('alternateNumber', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Alternate number')),
                ('upiId', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='finalResult',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.event')),
                ('colour', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('image', models.ImageField(blank=True, null=True, upload_to=accounts.models.user_directory_path, verbose_name='Profile Picture')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='Gender')),
                ('available_Balance', models.IntegerField(default=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Last Updated')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('withdrwaAmount', models.IntegerField()),
                ('status', models.CharField(max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('colour', models.CharField(choices=[('Red', 'Red'), ('Green', 'Green'), ('Blue', 'Blue')], max_length=5)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=8, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator('^[\\d]{10,12}$', message='Format (ex: 0123456789)')], verbose_name='Mobile Phone')),
                ('rechargeAmount', models.IntegerField()),
                ('UTR_num', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('paymentSentTo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.paymentpartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
