# Generated by Django 3.2.15 on 2023-01-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_paymentrecord_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='email',
            field=models.EmailField(max_length=255, null=True, verbose_name='Email Address'),
        ),
    ]
