# Generated by Django 3.2.15 on 2023-01-21 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_paymentrecord_paymentsentto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Bank', 'Bank')], max_length=20)),
                ('account_number', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('UPI_id', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='paymentSentTo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.paymentpartner'),
        ),
        migrations.DeleteModel(
            name='WithdrawalRecord',
        ),
    ]
