# Generated by Django 3.2.5 on 2023-02-27 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20230227_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
